CREATE TABLE "Attend" (
	"GID"	TEXT NOT NULL,
	"TID"	TEXT NOT NULL,
	"is_home_team"	bool,
	"Score"	INTEGER,
	"is_win_team"	TEXT,
	FOREIGN KEY("TID") REFERENCES "Team"("TID") ON UPDATE CASCADE,
	FOREIGN KEY("GID") REFERENCES "Game"("GID") ON UPDATE CASCADE,
	PRIMARY KEY("GID","TID")
);