CREATE TABLE "GameRecord" (
	"PID"	TEXT NOT NULL,
	"GID"	TEXT NOT NULL,
	"Assist"	INTEGER,
	"Hit"	INTEGER,
	"Steal"	INTEGER,
	"Rebound"	INTEGER,
	"Score"	INTEGER,
	"FreeThrow"	TEXT,
	PRIMARY KEY("PID","GID"),
	FOREIGN KEY("GID") REFERENCES "Game"("GID"),
	FOREIGN KEY("PID") REFERENCES "Player"("PID")
);