CREATE TABLE "GameRecord" (
	"PID"	INTEGER NOT NULL,
	"GID"	INTEGER NOT NULL,
	"Assist"	INTEGER,
	"Hit"	INTEGER,
	"Steal"	INTEGER,
	"Rebound"	INTEGER,
	"Score"	INTEGER,
	"FreeThrow"	INTEGER,
	PRIMARY KEY("PID","GID"),
	FOREIGN KEY("PID") REFERENCES "Player"("PID") ON DELETE CASCADE,
	FOREIGN KEY("GID") REFERENCES "Game"("GID") ON DELETE CASCADE
);